version: “3.9”
services:
  proxy:
    container_name: proxy
    image: nginx:${NGINX_VERSION}
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
    networks:
      - app-sfa-network

  frontend:
    container_name: frontend
    build: 
      context: ../
      dockerfile: app-sfa-infrastructure/docker/node/Dockerfile
      args:
        NODEJS_VERSION: ${NODEJS_VERSION}
    volumes:
      - ../app-sfa-frontend:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - app-sfa-network

  # db:
  #   container_name: fullstack-db
  #   build: ./docker/mysql
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
  #     - fullstack-db-volume:/var/lib/mysql
  #   environment:
  #     MYSQL_DATABASE: fullstack_db
  #     MYSQL_ROOT_PASSWORD: just1nnext
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: password

volumes:
  app-sfa-volume:

networks:
  app-sfa-network:
    driver: bridge