version: “3.9”
services:
  proxy:
    container_name: proxy
    image: nginx:${NGINX_VERSION}
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend
      - backend
    networks:
      - app-sfa-network

  frontend:
    container_name: frontend
    build: 
      context: ../
      dockerfile: app-sfa-infrastructure/docker/node/Dockerfile
      args:
        NODEJS_VERSION: ${NODEJS_VERSION}
    volumes:
      - ../app-sfa-frontend:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - app-sfa-network

  backend:
    container_name: backend
    build: 
      context: ../
      dockerfile: app-sfa-infrastructure/docker/php/Dockerfile
      args:
        PHP_VERSION: ${PHP_VERSION}
    volumes:
      - ../app-sfa-backend:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app-sfa-network
    depends_on:
    - db

  db:
    container_name: db
    image: mysql:${MYSQL_VERSION}
    ports:
      - 3306:3306
    volumes:
      # - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
      - app-sfa-volume:/var/lib/mysql
    environment:
      MYSQL_DATABASE: sfa
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password

volumes:
  app-sfa-volume:

networks:
  app-sfa-network:
    driver: bridge